FORMAT: 1A

# VUTTR API DOCUMENTATION
  Uma aplicação VUTTR (Very Useful Tools to Remember). A aplicação é um simples repositório para gerenciar ferramentas

# Group Authentication

## User [/users]

### Criar um usuário [POST]
+ Request(application/json)
    + Body 
        {
            "name": "user_name",
            "email": "user@email.com",
            "password": "password123",
        }

+ Response(application/json)
    + Body 
        {
            "id": "unic_id",
            "name": "user_name",
            "email": "user@email.com",
        }
        
## Sessions [/sessions]

### Autenticar usuário [POST]
+ Request (application/json)
    + Body
        {
            "email": "user@email.com",
            "password": "password123"
        }

+ Response (application/json)
    {
        "user": {
            "id": "unic_id",
            "name": "user_name",
            "email": "user@email.com"
        },
        "token": "user_token"
    }
    
# Group Tools

## Tools [/tools]

### Listar todas as ferramentas [GET]
  Buscar toda lista de ferramentas salvas.
+ Query (Opcional)
  + { tag="alguma_tag" }

+ Request 
  + Headers
    Authorization: Bearer { user_token } 


+ Response 200 (application/json)
  [
      {
        id: "5f19ff3b3d10052cbc8f2a85"
        title: "Notioan",
        link: "https://notion.so",
        description: "All in one tool to organize teams and ideas. Write, plan, collaborate, and get organized. ",
        tags: [
            "organization",
            "planning",
            "collaboration",
            "writing",
            "calendar"
        ]
      }
  ]


### Criar uma nova ferramenta [POST]
  Criar uma nova ferramenta em seu repositório.

+ Request (application/json)
    + Headers
      Authorization: Bearer { user_token } 

    + Body
        {
        "title": "hotel",
        "link": "https://github.com/typicode/hotel",
        "description": "Local app manager. Start apps within your browser, developer tool with local .localhost domain and https out of the box.",
        "tags":["node", "organizing", "webapps", "domain", "developer", "https", "proxy"]
        }

+ Response 201 (application/json)
   {
      "id": "5f1a0b32f305b540145a576c",
      "title": "hotel",
      "link": "https://github.com/typicode/hotel",
      "description": "Local app manager. Start apps within your browser, developer tool with local .localhost domain and https out of the box.",
      "tags":["node", "organizing", "webapps", "domain", "developer", "https", "proxy"],
  }

### Deletar uma ferramenta [DELETE]
  Deletar uma ferramenta especifica.

+ Parameters
  + tool_id (string) - Identificador da ferramenta que irá ser deletada.

+ Request
    + Headers
        Authorization: Bearer { user_token } 


+ Response 204
   No Content

+ Response 404

  {
    "status": "error",
    "message": "Tool not found"
  }

